services:
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - ./utfpr_classlog:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-network

  php:
    build:
      context: ./utfpr_classlog
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./utfpr_classlog:/var/www
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./classlog_frontend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./classlog_frontend/build:/var/www/frontend
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - app-network
    command: ["npm", "start"]

  db:
    image: mysql:8.4.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_USER: "$DB_USERNAME"
      MYSQL_PASSWORD: "$DB_PASSWORD"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
