#!/usr/bin/bash

set -o errexit
set -o pipefail

source .env

function ps {
    docker compose ps
}

function up {
    docker compose up "${@}"
}

function down {
    docker compose down "${@}"
}

function composer {
    docker run --rm --interactive                 \
     -e COMPOSER_CACHE_DIR="/app/.cache/composer" \
     -u "$(id -u):$(id -g)" -v "$(pwd):/app"      \
     -w /app composer:2.7.2 composer "${@}"
}

function nginx:check {
    docker compose exec web nginx -t
}

function nginx:status {
    docker compose exec web service nginx status
}

function nginx:reload {
   docker compose exec web nginx -s reload
}

function php:console {
    docker compose exec php php -a
}

function test {
   TEST_PATH="${@:-tests}"
   docker compose run --rm php ./vendor/bin/phpunit --color ${TEST_PATH}
}

function phpcs {
   TEST_PATH="${@:-.}"
   docker compose run --rm php ./vendor/bin/phpcs ${TEST_PATH}
}

function phpcbf {
   TEST_PATH="${@:-.}"
   docker compose run --rm php ./vendor/bin/phpcbf ${TEST_PATH}
}

function phpstan {
   TEST_PATH="${@:-}"
   docker compose run --rm php ./vendor/bin/phpstan ${TEST_PATH}
}

function git:clean:branchs {
  git branch | grep -v '\*\|master\|main\|develop\|production' | xargs -n 1 git branch -D
}

function db:console {
    docker compose exec db sh -c "MYSQL_PWD=${DB_PASSWORD} mysql -u ${DB_USERNAME} ${DB_DATABASE} --default-character-set utf8mb4"
}

function db:reset {
    docker compose cp database/schema.sql db:/tmp/
    docker compose exec db sh -c "MYSQL_PWD=${DB_PASSWORD} mysql -u ${DB_USERNAME} ${DB_DATABASE} --default-character-set utf8mb4 < /tmp/schema.sql"
}

function db:populate {
    docker compose exec php php database/Populate/populate.php
}

TIMEFORMAT=$'\nTask completed in %3lR'
time ${@}